#!/usr/bin/env bash
# This script displays numbers from 1 to 100 in list format
#   Display "FizzBuzz" if the number is a multiple of 3 and 5
#   Display "Fizz" if the number is a multiple of 3
#   Display "Buzz" if the number is a multiple of 5
#   Otherwise the number will b displayed

for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
completed
