#!/usr/bin/env bash
# This script displays the contents of the file /etc/passwdfile.
# Display only the username, user ID, and path to the user's home directory.

myfile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
